[platformio]
default_envs = goouuu-esp32-s3-cam

[env:goouuu-esp32-s3-cam]

platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

; ============================================================
; ESP32-S3 N16R8
; Flash: 16 MB QIO
; PSRAM: 8 MB OPI
; ============================================================

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

board_build.f_flash = 80000000L

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

board_build.partitions = default_16MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_ignore =
    Micropulsionador_inferencing

[env:ei-smoke-test]

platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

board_build.f_flash = 80000000L

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

board_build.partitions = default_16MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
    -<*>
    +<../diagnostics/ei-smoke-test/main.cpp>

lib_ignore =
    Micropulsionador_v2_inferencing
